[package]
name = "gpu-compute-example"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = "26.0.1"
bytemuck = { version = "1.23.2", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
flume = "0.11.0"
pollster = "0.4.0"
